name: Bug report
description: Report a bug
body:

- type: markdown
  attributes:
    value: |
      Please follow this template when reporting a bug.
      - Please search for existing similar issues first.
      - Please write a descriptive title.
      - Please create one issue per bug.

- type: textarea
  attributes:
    label: Version
    description: |
      - Please specify the version where you have found the issue.
    placeholder: |
      Version: 1.2.3-dev.
  validations:
    required: true

- type: textarea
  attributes:
    label: Description
    description: |
      Please describe the issue briefly. What doesn't work, and how would you expect it to work?
  validations:
    required: true

- type: textarea
  attributes:
    label: Steps to reproduce
    description: |
      Please provide a list of steps or a sample code that reproduces the issue.
  validations:
    required: true

- type: input
  attributes:
    label: System information
    description: |
      - If relevant, please specify Windows version, and hardware / drivers information.
    placeholder: Windows 11 - NVIDIA GeForce RTX 3070 (531.14)
  validations:
    required: false
