name: Feature request
description: Start a discussion about a new feature
body:

- type: markdown
  attributes:
    value: |
      Please follow this template when requesting a new feature.
      - Please search for existing similar requests first.
      - Please write a descriptive title.

- type: textarea
  attributes:
    label: Description
    description: |
      Please describe the proposed feature, its main use case, and its target audience.
  validations:
    required: true
